local EDialogue = {
    FirstScene0 = [[Everything is almost ready. I just need to install the <font color="#dbb23d"><b>batteries</b></font> and adjust the final settings of my <font color="#3ddbdb"><b>time machine</b></font>.]],
    FirstScene1 = [[Perfect... Now, let's pull the <font color="#dbb23d"><b>levers</b></font>.]],
    FirstScene2 = [[Everything's ready. I just need to press the <font color="#00b075"><b>button</b></font>...]],

    FirstSceneDoor0 = [[I shouldn't go out now; I must test the time machine. I have to put the <font color="#dbb23d"><b>battery</b></font> in its place...]],
    FirstSceneDoor1 = [[I shouldn't go out now; I must test the time machine. I have to pull the <font color="#dbb23d"><b>levers</b></font>.]],
    FirstSceneDoor2 = [[I shouldn't go out now; I must test the time machine. I just need to press the <font color="#00b075"><b>button</b></font>...]],

    SecondScene0 = [[Ugh, what a headache. It seems the time machine worked-only 30 minutes into the future-but it malfunctioned and doesn't seem to respond... Wait, why are the lights off?]],
    SecondScene1 = [[I can't see anything. The light switch should be right at the end of the stairs...]],
    SecondScene2 = [[<font size="35"><i>Oddly <font color="#00A2FF">futuristic</font>...</i></font> It seems I've jumped more than 30 minutes...]],
    SecondScene3 = [[Ooh, it opens with my fingerprint... It's my house, I know, but why is my fingerprint registered if I wasn't here?]],
    SecondScene4 = [[What's that smell? It seems to be coming from outside...]],
    SecondScene5 = [[What happened here? It's... it's all destroyed...]],

    SecondSceneDoor0 = [[I can't see anything, and I don't feel any handle. I need to turn on the lights...]],
    SecondSceneHurry0 = [[I need to hurry up]],

    ThirdScene0 = [[Did I jump again? Without the time machine? The time machine must have altered something in my body.]],
    ThirdScene1 = [[Jumping through time gives me a headache... <i>Focus!</i> I need to know what date it is. It appears the city is quite old, so I must be in the past.]],
    ThirdScene2 = [[Maybe in my house there is a <font color="#ee4b31"><b>calendar</b></font> or a <font color="#cbcbcb"><b>newspaper</b></font>.]],
    ThirdScene3 = [[It's very dark in here. I remember that the light switch was to the right of the double door.]],
    ThirdScene4 = [[Alright, this way I can search better...]],
    ThirdScene5 = [[Mmm... [26/02/1994] That's 30 years before I created the time machine.]],
    ThirdScene6 = [[Then the 30-minute jump must have encountered an error that sent it skyrocketing to 30 years.]],
    ThirdScene7 = [[Perhaps the timeline I landed in previously was set 30 years after I built the time machine, but that doesn't explain why everything was destroyed...]],

    ThirdSceneLights0 = [[I can't see anything, I need to turn on the lights of this room...]],
    ThirdSceneHurry0 = [[I need to hurry; I don't know when I'll jump again...]],

    FourthScene0 = [[Ugh, this headache is killing me. I need to find a solution for these jumps quickly.]],
    FourthScene1 = [[I need to look for some information about what happened here; maybe there's a <font color="#cbcbcb"><b>newspaper</b></font> nearby.]],
    FourthScene2 = [[Wait, what was that sound? It came from the 2nd floor.]],
    FourthScene3 = [[Dad?!]],
    FourthScene4 = [[Son! You're alive! I knew you couldn't have died. I searched everywhere for you, but I couldn't find you.]],
    FourthScene5 = [[Dad, I'm sorry-something went wrong. I'm stuck in this time loop... Dad... it's been so long... though only for you.]],
    FourthScene6 = [[A time loop...? I remember coming home one day and finding you gone. I waited, hoping you'd return, but when I went to the basement and saw that your time machine prototype wasn't there, I knew something had gone terribly wrong]],
    FourthScene7 = [[Time travel should feel instantaneous to those waiting, but you were gone for weeks. Desperate to find you, I attempted to build a time machine myself. However, I couldn't decipher your notes, so I sought help.]],
    FourthScene8 = [[I even published your research, hoping someone could rebuild your machine to bring you back. But someone misinterpreted your work and created the Time Chambers...]],
    FourthScene9 = [[Time Chambers...?]],
    FourthScene10 = [[They are spaces where time stands still-you can study for years, and when you leave, not a second will have passed. Initially, they were hailed as a breakthrough, but their creator had darker plans: to enslave people in time forever.]],
    FourthScene11 = [[Many rebelled, but with the power of the Time Chambers, no one could stop him. He was ruthless; now, I'm one of the last humans on Earth.]],
    FourthScene12 = [[He and his followers fled to another planet, leaving only chaos and a few rebels behind.]],
    FourthScene13 = [[No... Why publish my research?]],
    FourthScene14 = [[I'm sorry-I only wanted to find you. But now there's no time left. The only way to fix this is if one of us <u><font size="38" color="#FF00FF">never existed</font></u>.]],
    FourthScene15 = [[No, no, no, that would create a time paradox.]],
    FourthScene16 = [[Relax. I've calculated the outcome-after the explosion, everything should balance out.]],
    FourthScene17 = [[<font size="36" color="#FF4500"><b>Explosion?!?</b></font>]],
    FourthScene18 = [[There's no time. Take this gun-since you're in my room, I must be here too. Just do it. Trust me.]],
    FourthScene19 = [[I'm not sure I can...]],

    FourthSceneDoor0 = [[Now it's open... interesting.]],

    FifthScene0 = [[<font size="40" color="#FF0000"><b>AAAGH!</b></font> <i>The headache... Is my dad sleeping here? How did he know he was here?</i>]],
    FifthScene1 = [[<i>Just...</i>]],
    FifthScene2 = [[Do I really have to do it?!]],
    FifthScene3 = [[I don't have any other option, do I? Maybe I can't handle another jump...]],
    FifthScene4 = [[He promised that everything would be alright afterward...]],
    FifthScene5 = [[Can I trust him?! There's no other way...]],
    FifthScene6 = [[I just need to finish this quickly-without pain.]],
    FifthScene7 = [[Interesting... This is the 28,373rd time this has happened. Not a single sign that anything will change...]],
    FifthScene8 = [[This universe is quite... <i>interesting</i>. With the energy generated by the repeated paradox, it amasses enough power to recreate the Big Bang.]],
    FifthScene9 = [[It's a form of self-defense to overcome these defects in reality. But the universe is not sentient-it cannot think; it's like your immune system.]],
    FifthScene10 = [[And maybe sometimes it makes mistakes. Irreversible ones. For this universe, the number 10^(2736724*23873) is itself the cause of every misfortune.]],
    FifthScene11 = [[It doesn't discard the old; it just reuses them to craft something seemingly "new"-but not at its core... which means...]],
    FifthScene12 = [[That everything starts over-one battery at a time.]],
    FifthScene13 = [[Everything is almost ready. I just need to install the <font color="#dbb23d"><b>battery</b></font> and adjust the final settings of my <font color="#3ddbdb"><b>time machine</b></font>.]],
}

return EDialogue